workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        GRADLE_TASK: "assembleDebug"
    scripts:
      - name: Build Debug APK
        script: ./gradlew $GRADLE_TASK
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your@email.com
